name: 'Test, build, publish'
on:
  push:
    branches:
      - main
    pull_request:
    workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Node.js dependencies
    runs-on: ubuntu-latest
    env:
      cache-name: cache-node-modules
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Node
       uses: actions/setup-node@v3
       with:
         node-version: 16.14.0
     - name: Compute hash key
       id: hash-key
       run: echo "hash=${{ hashFiles('**/package-lock.json') }}" >> "$GITHUB_OUTPUT"
     - name: Cache Node modules
       id: cache-npm
       uses: actions/cache@v3
       with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.hash-key.outputs.hash }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

     - name: Install dependencies
       run: npm ci
    outputs:
      cache-key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.hash-key.outputs.hash }}

  check-prettier:
    name: Check Prettier formatting
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Node
       uses: actions/setup-node@v3
       with:
         node-version: 16.14.0
     - name: Restore dependencies
       uses: actions/cache@v3
       with:
         path: node_modules
         key: ${{ needs.install-dependencies.outputs.cache-key }}
     - name: Check prettier formatting
       run: npm run format:check

  check-types:
    name: Check TypeScript
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Node
       uses: actions/setup-node@v3
       with:
         node-version: 16.14.0
     - name: Restore dependencies
       uses: actions/cache@v3
       with:
         path: node_modules
         key: ${{ needs.install-dependencies.outputs.cache-key }}
     - name: Check types
       run: npx tsc

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Node
       uses: actions/setup-node@v3
       with:
         node-version: 16.14.0
     - name: Restore dependencies
       uses: actions/cache@v3
       with:
         path: node_modules
         key: ${{ needs.install-dependencies.outputs.cache-key }}
     - name: Run unit tests
       run: npm run test

  publish-pages:
    name: Publish documentation to GitHub Pages
    needs: [install-dependencies]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ needs.install-dependencies.outputs.cache-key }}
      - name: Build documentation
        run: npm run build:docs
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/'
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
  # publish:
  #   name: Publish to npm
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   needs: [install-dependencies, check-prettier, run-unit-tests, check-types]
  #   runs-on: ubuntu-latest
  #   steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v3
  #      with:
  #       fetch-depth: 0
  #    - name: Set up Node
  #      uses: actions/setup-node@v3
  #      with:
  #        node-version: 16.14.0
  #    - name: Restore dependencies
  #      uses: actions/cache@v3
  #      with:
  #        path: node_modules
  #        key: ${{ needs.install-dependencies.outputs.cache-key }}
  #    - name: Build the package
  #      run: npm run build
  #    - name: Run semantic release bot
  #      run: npx semantic-release
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
